name: Build
on:
  workflow_dispatch:       # Allow running the workflow manually from the GitHub UI
  push:
    branches: [ 'main' ]   # Run the workflow when pushing to the main branch
  pull_request:
    branches: [ '*' ]      # Run the workflow for all pull requests
  release:
    types: [ published ]   # Run the workflow when a new GitHub release is published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-node@v4
          with:
            node-version: 20.x
        - uses: actions/checkout@v4.1.6
        - name: Run unit tests
          run:  |
            npm install
            npm uninstall --save-dev mocha
            npm install --save-dev mocha
            npm test

    e2e-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Get current tag
          id: tag
          run: |
            git fetch --tags
            latest_tag=$(git tag --list --sort=-version:refname "v*" | head -n 1)
            echo "tag=${latest_tag}" >> $GITHUB_OUTPUT

        - name: Generate next tag
          id: next_tag
          uses: SimpleBitware/next-tag@v1.0.0
          with:
            preserve_v: true
            current_tag: ${{ steps.tag.outputs.tag }}
