name: Build
on:
  workflow_dispatch:       # Allow running the workflow manually from the GitHub UI
  push:
    branches: [ 'main' ]   # Run the workflow when pushing to the main branch
  pull_request:
    branches: [ '*' ]      # Run the workflow for all pull requests
  release:
    types: [ published ]   # Run the workflow when a new GitHub release is published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/setup-node@v4
          with:
            node-version: 20.x
        - uses: actions/checkout@v4.1.6
        - name: Run unit tests
          run: |
            npm install
            npm run build
            npm test

    e2e-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Get current tag
          id: tag
          uses: devops-actions/action-get-tag@v1.0.3
          with:
            strip_v: true
            default: v0.0.0

        - name: Generate next tag
          id: next_tag
          uses: SimpleBitware/next-tag@v1.0.0
          with:
            preserve_v: true
            current_tag: ${{ steps.tag.outputs.tag }}
            
        - name: Use next_tag
          run: echo ${{steps.next_tag.outputs.tag}}
